background {
    monitor =
    path    = ~/Pictures/Wallpapers/macos.jpg
    blur_passes = 3
    blur_size   = 8
    contrast    = 0.9
    brightness  = 0.7
}

input-field {
    monitor      =
    size         = 280, 50
    outline_thickness = 2
    rounding     = 25
    outer_color  = rgba(ffffff44)
    inner_color  = rgba(00000088)
    font_color   = rgb(ffffff)
    fade_on_empty = true
    placeholder_text = <i>Contraseña…</i>
    position     = 0, -80
    halign       = center
    valign       = center
}

label {
    monitor   =
    text      = cmd[update:1000] echo "$(date +'%H:%M')"
    color     = rgba(ffffffee)
    font_size = 96
    font_family = JetBrainsMono Nerd Font
    position  = 0, 200
    halign    = center
    valign    = center
}

label {
    monitor   =
    text      = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    color     = rgba(ffffffcc)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position  = 0, 100
    halign    = center
    valign    = center
}
